using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerData : MonoBehaviour
{
    #region singleton
    public static PlayerData instance;
    private void Awake()
    {
        if (instance == null)
            instance = this;
    }
    #endregion


    //Scripts
    public LevelSystem _levelSystem;
    public Upgradeables _upgradeables;

    //Saved variables
    //levels
    public int _Level;
    int DefaultLevel = 1;
    public float _currentXP;
    float DefaultCurrentXp = 0;
    public int _nextLevelXp;
    int DefaultNextLevelXp = 0;
    public int _xpPoints;
    int DefaultXpPoints = 0;

    //upgrades
    int DefaultUpgradeLevel = 0;

    #region Items
    public Item explosion;
    public int _explosionLevel;


    public Item Damage;
    public int _damageLevel;

    public Item fireRate;
    public int _fireRateLevel;

    public Item Ricochet;
    public int _ricochetLevel;

    public Item SpeedUp;
    public int _speedLevel;

    public Item Duplicate;
    public int _duplicateLevel;

    public Item Crit;
    public int _critLevel;

    public Item Spread;
    public int _spreadLevel;

    public Item Freeze;
    public int _freezeLevel;

    public Item Big;
    public int _bigLevel;

    public Item Pierce;
    public int _pierceLevel; 
    #endregion

    public static int TutorialComplete = 0;
    int tutorialDefault = 0;

    

    public void Start()
    {
        LoadData(); 
       

        _levelSystem.level = _Level;
        _levelSystem.currentXp = _currentXP;
        _levelSystem.nextLevelXp = _nextLevelXp;
        _levelSystem.EXPpoints = _xpPoints;

        //Upgrades
        
        explosion.level = _explosionLevel;
        explosion.UpgradeAmount = 0;
        explosion.baselevel = 0;
        explosion.UpdateUpgrade();

        Damage.level = _damageLevel;
        Damage.UpgradeAmount = 0;
        Damage.baselevel = 0;
        Damage.UpdateUpgrade();

        fireRate.level = _fireRateLevel;
        fireRate.UpgradeAmount = 0;
        fireRate.baselevel = 0;
        fireRate.UpdateUpgrade();

        Ricochet.level = _ricochetLevel;
        Ricochet.UpgradeAmount = 0;
        Ricochet.baselevel = 0;
        Ricochet.UpdateUpgrade();

        SpeedUp.level = _speedLevel;
        SpeedUp.UpgradeAmount = 0;
        SpeedUp.baselevel = 0;
        SpeedUp.UpdateUpgrade();

        Duplicate.level = _duplicateLevel;
        Duplicate.UpgradeAmount = 0;
        Duplicate.baselevel = 0;
        Duplicate.UpdateUpgrade();

        Crit.level = _critLevel;
        Crit.UpgradeAmount = 0;
        Crit.baselevel = 0;
        Crit.UpdateUpgrade();

        Spread.level = _spreadLevel;
        Spread.UpgradeAmount = 0;
        Spread.baselevel = 0;
        Spread.UpdateUpgrade();

        Freeze.level = _freezeLevel;
        Freeze.UpgradeAmount = 0;
        Freeze.baselevel = 0;
        Freeze.UpdateUpgrade();

        Big.level = _bigLevel;
        Big.UpgradeAmount = 0;
        Big.baselevel = 0;
        Big.UpdateUpgrade();

        Pierce.level = _pierceLevel;
        Pierce.UpgradeAmount = 0;
        Pierce.baselevel = 0;
        Pierce.UpdateUpgrade(); 
        
    }

    private void Update()
    {
        _Level = _levelSystem.level;
        _currentXP = _levelSystem.currentXp;
        _nextLevelXp = _levelSystem.nextLevelXp;
        _xpPoints = _levelSystem.EXPpoints;


        
        _explosionLevel = explosion.level;
        _damageLevel = Damage.level;
        _fireRateLevel = fireRate.level;
        _ricochetLevel = Ricochet.level;
        _speedLevel = SpeedUp.level;
        _duplicateLevel = Duplicate.level;
        _critLevel = Crit.level;
        _spreadLevel = Spread.level;
        _freezeLevel = Freeze.level;
        _bigLevel = Big.level;
        _pierceLevel = Pierce.level; 
        


    }
    public void LoadData()
    {
        TutorialComplete = ES3.Load("TutorialComplete", tutorialDefault);
        _Level = ES3.Load("SavedLevel", DefaultLevel);
        _currentXP = ES3.Load("SavedXp", DefaultCurrentXp);
        _nextLevelXp = ES3.Load("NextLevelXp", DefaultNextLevelXp);
        _xpPoints = ES3.Load("XPPoints", DefaultXpPoints);

        
        _explosionLevel = ES3.Load("ExplosionUpgradeLevel", DefaultUpgradeLevel);
        _damageLevel = ES3.Load("DamageUpgradeLevel", DefaultUpgradeLevel);
        _fireRateLevel = ES3.Load("FireRateUpgradeLevel", DefaultUpgradeLevel);
        _ricochetLevel = ES3.Load("RicochetUpgradeLevel", DefaultUpgradeLevel);
        _speedLevel = ES3.Load("SpeedUpgradeLevel", DefaultUpgradeLevel);
        _duplicateLevel = ES3.Load("DuplicateUpgradeLevel", DefaultUpgradeLevel);
        _critLevel = ES3.Load("CritUpgradeLevel", DefaultUpgradeLevel);
        _spreadLevel = ES3.Load("SpreadUpgradeLevel", DefaultUpgradeLevel);
        _freezeLevel = ES3.Load("FreezeUpgradeLevel", DefaultUpgradeLevel);
        _bigLevel = ES3.Load("BigUpgradeLevel", DefaultUpgradeLevel);
        _pierceLevel = ES3.Load("PierceUpgradeLevel", DefaultUpgradeLevel); 
        
    }

    public void SaveData()
    {
        ES3.Save("SavedLevel", _Level);
        ES3.Save("SavedXp", _currentXP);
        ES3.Save("NextLevelXp", _nextLevelXp);
        ES3.Save("XPPoints", _xpPoints);

        
        ES3.Save("ExplosionUpgradeLevel", _explosionLevel);
        ES3.Save("DamageUpgradeLevel", _damageLevel);
        ES3.Save("FireRateUpgradeLevel", _fireRateLevel);
        ES3.Save("RicochetUpgradeLevel", _ricochetLevel);
        ES3.Save("SpeedUpgradeLevel", _speedLevel);
        ES3.Save("DuplicateUpgradeLevel", _duplicateLevel);
        ES3.Save("CritUpgradeLevel", _critLevel);
        ES3.Save("SpreadUpgradeLevel", _spreadLevel);
        ES3.Save("FreezeUpgradeLevel", _freezeLevel);
        ES3.Save("BigUpgradeLevel", _bigLevel);
        ES3.Save("PierceUpgradeLevel", _pierceLevel); 
        

    }


}
